image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-debian:9-master-75925678
stages:
  - test
docs:
  stage: test
  script:
  - env BST_SOURCE_CACHE="$(pwd)/cache/integration-cache/sources" tox -e docs
  - mv doc/build/html public
  artifacts:
    paths:
    - public/
